---
# Lint directives.
lint:
  # Linter files to ignore.
  ignores:
    - id: ENUM_FIELDS_HAVE_COMMENT
      files:
        - proto/ate.proto

  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules:
    # Determines whether or not to include the default set of linters.
    #no_default: true

    # Set the default to all linters. This option works the other way around as no_default does.
    # If you want to enable this option, delete the comment out below and no_default.
    all_default: true

    # The specific linters to remove.
    remove:
      - ENUM_FIELD_NAMES_PREFIX
      - ENUMS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT

  # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 160
      # Specifies the character count for tab characters
      tab_chars: 2

    # INDENT rule option.
    indent:
      # Available styles are 4(4-spaces), 2(2-spaces) or tab.
      style: 2
      # Specifies if it should stop considering and inserting new lines at the appropriate positions
      # when the inner elements are on the same line. Default is false.
      not_insert_newline: true
